### ISSUE TITLE
is jQuery needed?

### ISSUE THREAD

**Issue by SergioCrisostomo** [froala/vue-froala-wysiwyg#1]
Hi!

Is jQuery a dependency needed in the core editor? is it possible to separate core functionality from DOM stuff so we can use the vue.js version and not have jQuery as a dependency?

cheers

**Comment by stefanneculai** [comment]
At this moment the editor requires jQuery. We're working on removing it as a dependency and there will be an update shortly.

**Comment by jackbarham** [comment]
I presume jQuery is longer required now? https://github.com/froala/vue-froala-wysiwyg/commit/d061484d7a35fbd0292ce43f128645e177d79fe6

**Comment by jackbarham** [comment]
Any news on this?
