### ISSUE TITLE
TypeError: Vue.component is not a function

### ISSUE THREAD

**Issue by lbjones** [froala/vue-froala-wysiwyg#10]
I'm following the example to add froala to a .vue component.  It compiled with no errrors, but I get a runtime error:

> `Error in render function: "TypeError: Vue.component is not a function"`

Anyone have ideas of what I may have missed?

**Comment by stefanneculai** [comment]
@lbjones it appears to be the same with https://forum.vuejs.org/t/trouble-with-webpack/8986/2.
