### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by OctaneInteractive** [froala/vue-froala-wysiwyg#104]
Hi!

Having followed the instructions down to step 2, I'm getting the following errors on the command line:

> These dependencies were not found:
> 
> * @babel/runtime-corejs2/core-js/json/stringify in ../node_modules/vue-froala-wysiwyg/es/vue-froala.js
> * @babel/runtime-corejs2/core-js/object/define-property in ../node_modules/vue-froala-wysiwyg/es/index.js, ../node_modules/vue-froala-wysiwyg/es/vue-froala.js
> * @babel/runtime-corejs2/helpers/interopRequireDefault in ../node_modules/vue-froala-wysiwyg/es/index.js, ../node_modules/vue-froala-wysiwyg/es/vue-froala.js
> 
> To install them, you can run: npm install --save @babel/runtime-corejs2/core-js/json/stringify @babel/runtime-corejs2/core-js/object/define-property @babel/runtime-corejs2/helpers/interopRequireDefault

... and these errors in the browser:

> [HMR] bundle has 5 errors
> ../node_modules/vue-froala-wysiwyg/es/vue-froala.jsModule not found: Error: Can't resolve '@babel/runtime-corejs2/core-js/json/stringify' in '/path_to_project/node_modules/vue-froala-wysiwyg/es'../node_modules/vue-froala-wysiwyg/es/index.jsModule not found: Error: Can't resolve '@babel/runtime-corejs2/core-js/object/define-property' in '/path_to_project/node_modules/vue-froala-wysiwyg/es'../node_modules/vue-froala-wysiwyg/es/vue-froala.jsModule not found: Error: Can't resolve '@babel/runtime-corejs2/core-js/object/define-property' in '/path_to_project/node_modules/vue-froala-wysiwyg/es'../node_modules/vue-froala-wysiwyg/es/index.jsModule not found: Error: Can't resolve '@babel/runtime-corejs2/helpers/interopRequireDefault' in '/path_to_project/node_modules/vue-froala-wysiwyg/es'../node_modules/vue-froala-wysiwyg/es/vue-froala.jsModule not found: Error: Can't resolve '@babel/runtime-corejs2/helpers/interopRequireDefault' in '/path_to_project/node_modules/vue-froala-wysiwyg/es'

I'm reluctant to go messing around with Babel, and less inclined to do so when there's no mention of having to do this.

Some guidance would be much appreciated.

**Comment by afwn90cj93201nixr2e1re** [comment]
> To install them, you can run: npm install --save @babel/runtime-corejs2/core-js/json/stringify @babel/runtime-corejs2/core-js/object/define-property @babel/runtime-corejs2/helpers/interopRequireDefault

did you tried?

**Comment by afwn90cj93201nixr2e1re** [comment]
Just open dir node_modules\vue-froala-wysiwyg\es it's using when you using import, so, you must use  node_modules\vue-froala-wysiwyg\dist which already compiled.

**Comment by OctaneInteractive** [comment]
Hi @afwn90cj93201nixr2e1re, as I explained, I'd prefer not to install plugins for Babel when the installation instructions make no mention of this — if I break Babel, I risk breaking the entire application.

**Comment by OctaneInteractive** [comment]
I tried and got another error:

> npm ERR! code ENOLOCAL
> npm ERR! Could not install from "@babel/runtime-corejs2/core-js/json/stringify" as it does not contain a package.json file.

I don't have a good understanding of Babel.

**Comment by afwn90cj93201nixr2e1re** [comment]
Show how you importing files.
@OctaneInteractive

**Comment by OctaneInteractive** [comment]
As per the [instructions](https://github.com/froala/vue-froala-wysiwyg/#1-require-and-use-froala-editor-component-inside-your-application).

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/froala/vue-froala-wysiwyg/issues/104#issuecomment-520209687

import VueFroala from 'vue-froala-wysiwyg/dist/vue-froala.min.js'
try this

**Comment by OctaneInteractive** [comment]
Working.

So is this something wrong with the installation, or the actual package itself?

**Comment by afwn90cj93201nixr2e1re** [comment]
Here's nothing wrong.
If you're using es6 imports its gonna take sources, so, now u r using dist, which already compiled.

https://github.com/froala/vue-froala-wysiwyg/issues/104#issuecomment-520209687
