### ISSUE TITLE
Cannot read property 'set' of undefined.

### ISSUE THREAD

**Issue by jaesung2061** [froala/vue-froala-wysiwyg#111]
[This line](https://github.com/froala/vue-froala-wysiwyg/blob/master/src/vue-froala.js#L129) is causing the following error.

```
vue-froala.js?86a1:111 Uncaught TypeError: Cannot read property 'set' of undefined
    at htmlSet (vue-froala.js?86a1:111)
    at E.Bootstrap.eval (vue-froala.js?86a1:121)
    at E.Bootstrap.currentConfig.events.initialized (vue-froala.js?86a1:260)
    at Object.v [as trigger] (froala_editor.min.js?b1fc:7)
    at E.Bootstrap.S (froala_editor.min.js?b1fc:7)
```

This doesn't look like it's causing any actual bugs, but the error message is really annoying when developing.

**Comment by jwhitmarsh** [comment]
Are you binding v-model to an undefined (or defined in a Promise) variable? I had to manually initialise Froala on the `$nextTick` after setting the v-model data.

**Comment by jaesung2061** [comment]
I reset all my changes and tried again and this issue seems to be resolved. I'm not entirely sure what I did wrong in the first place.
