### ISSUE TITLE
ReferenceError: $ is not defined     at VueComponent.createEditor

### ISSUE THREAD

**Issue by law0118** [froala/vue-froala-wysiwyg#14]
i have some trouble when i want to use Froala, 
app.js:1732 ReferenceError: $ is not defined
    at VueComponent.createEditor (app.js:26430)
    at VueComponent.boundFn [as createEditor] (app.js:1374)
    at VueComponent.mounted (app.js:26378)
    at callHook (app.js:3765)
    at Object.insert (app.js:4592)
    at invokeInsertHook (app.js:6420)
    at Vue$3.patch [as __patch__] (app.js:6585)
    at Vue$3.Vue._update (app.js:3525)
    at Vue$3.updateComponent (app.js:3648)
    at Watcher.get (app.js:3987)

**Comment by v-Stein** [comment]
This is because you don't have jQuery with the global alias '$'.
If you already installed jQuery, `try window.$ = jQuery;`

**Comment by stefanneculai** [comment]
As @v-Stein said, you should have jQuery defined globally. The best way would be to add it as a plugin to Webpack config:
```js
plugins: [

    // ...

    // Jquery loader plugin.
    new webpack.ProvidePlugin({
      $: "jquery",
      jQuery: "jquery"
    })
  ]
```

**Comment by waqaar145** [comment]
Hi @law0118  
Did u manage to use froala in your application, I am having same problem ... I am using vue-cli and i dont see any webpack.config.js file 
Can u please help how exactly did you manage to solve this issue , Thanks

**Comment by syed-haroon** [comment]
For the users who are using `vue-cli-3`:
Create `vue.config.js` in root and place this code:

```
const webpack = require('webpack');

module.exports = {
  configureWebpack: {
    plugins: [
      new webpack.ProvidePlugin({
        $: 'jquery',
        jQuery: 'jquery',
        'window.jQuery': 'jquery'
      })
    ]
  }
}

// use either of the code written above or below, both work the same.

module.exports = {
  chainWebpack: config => {
    config
      .plugin('provide')
      .use(webpack.ProvidePlugin, [{
        $: 'jquery',
        jquery: 'jquery',
        jQuery: 'jquery',
        'window.jQuery': 'jquery'
      }]);
  },
};
```

**Comment by JesseBlackman** [comment]
@syed-haroon you are right, thank you
