### ISSUE TITLE
Vue v3 compatibility

### ISSUE THREAD

**Issue by NoahStahl** [froala/vue-froala-wysiwyg#144]
Now that Vue version 3 is in release candidate stage and due out soon, will this library be updated to ensure it works with the new major version? Thanks!

https://github.com/vuejs/rfcs/issues/189

**Comment by LaravelFreelancerNL** [comment]
Vue 3.0 stable has been released. Is there an ETA for this package to be upgraded to it?

**Comment by LaravelFreelancerNL** [comment]
Any news?

**Comment by NoahStahl** [comment]
I'll go ahead and close this since it's clearly ignored and I've already moved to TinyMCE which does maintain a solid Vue integration.

**Comment by hdtopku** [comment]
很遗憾，不支持vue3
