### ISSUE TITLE
All events not working in v3.2.1

### ISSUE THREAD

**Issue by arwinvdv** [froala/vue-froala-wysiwyg#149]
We updated the project to v3.2.1, but we found out that ALL events are not working anymore. 
And we understand why….. https://github.com/froala/vue-froala-wysiwyg/compare/v.3.2.0...v3.2.1

Hopefully you will fix this soon so we can work with the newest version.

Example, the contentChanged event and initialized event is not working: https://codesandbox.io/s/vue-froala-eynx5?file=/src/App.vue

**Comment by arwinvdv** [comment]
Got reaction of Froala support: 
> This issue is already submitted to development, but a timeline has not yet been established for a fix.

**Comment by armadillo-dev** [comment]
same issue here!

**Comment by MangeshPimpalkar** [comment]
There needs to be a watch on the "config". 
The events added dynamically is not added to the config and hence not triggered.
The same happened to me after adding the config to watch it works fine.

 ```
watch: {
      value: function() {
         ...
      },
      config: {
        deep: true,
        handler(newVal) {
          this.currentConfig = newVal;
        }
      }
    },
```

for eg I want to initialize only when all my config is updated hence I call.
```
 methods: {
    initialize(initControls) {
      console.log(this.config);
      this.initControls = initControls;
      this.initControls.initialize();
    }
  }
```
but when you check this.config it will always show the old config. 
It took me 1 day to figure out why the code was not working until I checked the library source code.

For now, I have copied the code to my repository. Waiting for updation. Thanks

**Comment by developcodeza-chris** [comment]
Same here. Downgraded from 3.2.1 to 3.2.0 for now.

**Comment by arwinvdv** [comment]
Looks like fixed in https://github.com/froala/vue-froala-wysiwyg/releases/tag/v3.2.1-1
