### ISSUE TITLE
Vue.Js 3.x support

### ISSUE THREAD

**Issue by Xoben** [froala/vue-froala-wysiwyg#168]
Does someone have a timeline on when Froala will support Vue.Js 3.x

https://v3.vuejs.org/

**Comment by iissy** [comment]
I want to know what is plan for vue 3.x

**Comment by vankizmann** [comment]
For the time being you can try my fork https://github.com/froala/vue-froala-wysiwyg/pull/170

Dunno why no one is responding to the request.

**Comment by SimonOrdo** [comment]
An update to VueJs 3 sure would be nice right around now.

**Comment by mstikharev** [comment]
Hello guys, how we can speed up this issue. It's very important for us to upgrade froala supporting vue3. We are paying you for plugin but we can't get fresh updates. Can you pls do something????

**Comment by olemarius** [comment]
We're upgrading our legacy website to vue 3 and lacking vue 3 support from froala is becoming a more and more critical blocker. Ilyas Karim from support told me Vue 3 will be supported from 3.3.1 but instead it seems froala jumped from 3.2.7 to 4.0. 

If vue 3 wont be prioritized, please let us know so we can look at other options.

**Comment by allmanaj** [comment]
Will there be any update on Vue 3 support in the future?

**Comment by Xoben** [comment]
I really need Vue JS 3 support for Froala. I am a paying customer and have been waiting patiently for the update.  If you unable to support Vue 3 please let us know so I can find a different product.

**Comment by blankTwo** [comment]
> 我真的需要 Vue JS 3 支持 Froala。我是付费用户，一直在耐心等待更新。如果您无法支持 Vue 3，请告诉我们，以便我可以找到不同的产品。

Do you have a good product recommendation

**Comment by blankTwo** [comment]
> I really need Vue JS 3 support for Froala. I am a paying customer and have been waiting patiently for the update. If you unable to support Vue 3 please let us know so I can find a different product.

Do you have a good product recommendation

**Comment by dmhendricks** [comment]
> Do you have a good product recommendation

I had recommended `tinymce-vue` to them, but the company decided to stay with Froala because they're already paying for it. 😕 It probably depends on what kind of functionality/plugins you need, and also budget since TinyMCE isn't cheap either (if you need the functionality of any of the premium plugins).

I tried to convert `vue-froala-wysiwyg` to Vue 3 but was unsuccessful since I'm novice.

**Comment by woro14** [comment]
any updates?

**Comment by J-HernandezInzunza** [comment]
Bummer there is no Vue 3 support still, I'll have to find an alternative

**Comment by Woeler** [comment]
Any update? Vue3 is default now, we could really go with an update on the status of this.

**Comment by imuller** [comment]
Any update on this??

**Comment by jfk00ca** [comment]
Vue 3 - it's been 15 months since the question was asked and as everyone has said, this is now the standard and you are holding the developer community who chose Froala back not having Vue 3 compatibility. CKeditor has Vue 3 support, TinyMCE has Vue 3 support (as long back as 2020 according to their blog!), as do others. Please let everyone know when we can expect Vue 3 support.

**Comment by joostelders** [comment]
I've contacted Froala support a while ago and they told me that Vue 3 will be fully supported in Froala version 4.1, which they're expecting to release in Q3 this year.

So it's hopefully going to happen in the next couple of months..

**Comment by szabizs** [comment]
Until this is solved by the Froala team, here is my solution, it's kind of reactive based on the Froala events.


```
<script setup>

import { reactive } from 'vue'

import "froala-editor/css/froala_editor.pkgd.min.css"
import FroalaEditor from "froala-editor/js/froala_editor.pkgd.min.js"

let post = reactive({
    content: ''
})

function initFroala() {
    new FroalaEditor("#froala", {
        inlineMode: false,
        pastePlain: true,
        paragraphy: false,
        quickInsertEnabled: false,
        toolbarButtons: {
            // Key represents the more button from the toolbar.
            moreText: {
                // List of buttons used in the  group.
                buttons: ['clearFormatting'],
                // Alignment of the group in the toolbar.
                align: 'left',
                // By default, 3 buttons are shown in the main toolbar. The rest of them are available when using the more button.
                buttonsVisible: 1
            },
            moreParagraph: {
                buttons: ['alignLeft', 'alignJustify', 'formatOLSimple', 'formatOL', 'formatUL'],
                align: 'left',
                buttonsVisible: 6
            },
            moreMisc: {
                buttons: ['undo', 'redo', 'fullscreen', 'print', 'selectAll'],
                align: 'right',
                buttonsVisible: 5
            }
        },
        // Change buttons for XS screen.
        toolbarButtonsXS: [['undo', 'redo'], ['bold', 'italic', 'underline']],
        placeholderText: $t('describe_thread'),
        attribution: false,
        key: 'enter-your-license-key-here',
        disableRightClick: true,
        height: 130,
        fileUpload: false,
        imageUpload: false,
        imagePaste: false,
        imagePasteProcess: false,
        imageResize: false,
        crossDomain: false,
        events: {
            onSelectionChange: function() { // I need something like this.
                post.content = this.html.get()
            },
            'keyup': function (inputEvent) {
                post.content = this.html.get()
            },'click': function (clickEvent) {
                post.content = this.html.get()
            },
            'commands.after': function (cmd, param1, param2) {
                post.content = this.html.get()
            },
            'paste.after': function (pasteEvent) {
                post.content = this.html.get()
            }
        }
    })
}


onMounted(() => {
    initFroala()
})

</script>
```

**Comment by bakadest** [comment]
Any updates regarding this? Vue3 is a new default for at least of 8 months. I just can't understand what is taking you so long.

**Comment by szabizs** [comment]
> Any updates regarding this? Vue3 is a new default for at least of 8 months. I just can't understand what is taking you so long.

The fact that we've paid for this plugin, should have considerably greater support than this.

**Comment by Woeler** [comment]
> > Any updates regarding this? Vue3 is a new default for at least of 8 months. I just can't understand what is taking you so long.
> 
> The fact that we've paid for this plugin, should have considerably greater support than this.

Our business is now in the process of moving away from Froala in every project we have. This major issue lingering so long, without proper statements and timelines, is simply unacceptable for a paid (and expensive!) product like Froala.

**Comment by joostelders** [comment]
This is taking way too long. Can anyone advice a good (similar) alternative?

**Comment by SimonOrdo6** [comment]
I'm pretty sure "Froala" is just a small subsidiary team at "Idera, Inc".  Since the Froala team seems to be all but unresponsive to inquiries, has anyone by chance attempted to contact anyone at the main office to see if they have any clarity on subject?
https://www.ideracorp.com/contactus

I consider vendors that provide project critical libraries as business partners, and it's difficult to make any forward leaning decisions when a non-trivial vendor just goes radio silent.

**Comment by huchoi90** [comment]
I think I've waited quite a while 

Still no plans to support vue 3?

**Comment by jfk00ca** [comment]
I agree 100% that this is totally unacceptable - we are also extremely very frustrated. 

Our lead developer spent over a week fixing a bug with the way Froala managed multiple toolbars using iframes, submitted it to Froala back in May and as of the last update it is still not included in the latest build, so he is having to patch Froala manually every time we do an update. It’s bad enough paying major $$$ for a product, but then also paying *our* developers to fix bugs and not even seeing them included in the updates... horrible.

**Comment by yohoGDES** [comment]
At this point we as a community should either look to fork and resolve this ourselves or suggest some recommendations for a replacement. Vue 3 came out in 2020 and it's almost 2023, Froala either can't keep up with the demand or this isn't a priority for them.

If anyone from the Froala support team can tell us what issues you're facing in this feature release perhaps we can contribute solutions.

**Comment by SimonOrdo6** [comment]
From Froala Customer Support:

> My apologies for the delayed response. I just got feedback from the dev team.
> We are expecting the 4.1 major Release by December.
>  
> Thank you for your patience. 
> 

Believe that as you will.  Either way, probably not a good sign for future support,  given the delay between the Vue3 release and the Froala release.  It just doesn't seem like it's a priority for them to support Vue.

**Comment by jfk00ca** [comment]
I agree 100% that this is totally unacceptable - we are also extremely very frustrated. 

 

Our lead developer spent over a week fixing a bug with the way Froala managed multiple toolbars on one screen, submitted it to Froala back in May and as of the last update it is still not included in the latest build, so he is having to patch Froala manually every time we do an update. It’s bad enough paying major $$$ for a product, but then also paying *our* developers to fix bugs and not even seeing them included in the updates, horrible.

**Comment by szabizs** [comment]
We have migrated to [TipTap](https://tiptap.dev/)

**Comment by Woeler** [comment]
And we have migrated to EditorJS.

**Comment by jfk00ca** [comment]
It's been almost another 2 months - any update on this? 

Vue 3 integration was promised to in Froala V4.1, which was was supposed to be ready for the START of the 3rd quarter.
"Unfortunately, we do not support Vue 3 officially. This integration will be fully supported in version 4.1. The V4.1  is expected to be released by the start of the third quarter."

**Comment by yigitkonur** [comment]
Any update?

**Comment by paulogiacomelli** [comment]
From froala team: Support will come with 4.1 release which is "coming in next quarter". After clarification, froala team said: "mid-quarter".

**Comment by juuuuuuuuuuuuuu** [comment]
You mean version 4.1 will come out in the beginning of the third quarter of 2023?
There is still a long time left

**Comment by paulogiacomelli** [comment]
> You mean version 4.1 will come out in the beginning of the third quarter of 2023? There is still a long time left

Meaning: May-ish.

**Comment by roelVerdonschot** [comment]
We are also waiting for this package to support Vue3

**Comment by biancadellarosa** [comment]
still no update?

**Comment by DevMakoto** [comment]
still no update?

**Comment by AustinW** [comment]
We are also waiting for Vue 3 support. Any word?

**Comment by brad-idr** [comment]
You're going to keep losing paying customers if you don't address this, or at the very least, keep us posted

**Comment by zdravkov** [comment]
Kando UI for Vue is a good alternative if you are looking for a commercial component in Vue 3 - https://www.telerik.com/kendo-vue-ui/components/editor/

**Comment by jfk00ca** [comment]
Any update on the Vue 3 integration release date? Are you on track for May 15 as per your earlier email communication?

**Comment by jfk00ca** [comment]
With Vue 2's EOL this year the community desperately needs Vue 3 compatibility in Froala and you originally promised it for Q4 2022. When will Vue 3 support be released? Not getting a clear answer we can depend on is very frustrating.

**Comment by mabdullahsari** [comment]
We've decided to ditch Froala in favor of another editor.

**Comment by szabizs** [comment]
Check this out guys - https://github.com/ckeditor/ckeditor5-vue

**Comment by markr512** [comment]
官网说了预计6月发布4.1,看看是否继续放鸽子

**Comment by crysper** [comment]
We wanted to buy the $3,000 perpetual license for our SaaS but we dissapointedly find out they don't have a vue 3 version and also don't keep their promises.

I see the 4.1 version in RC for vue 3, any news when this will be released fully?

**Comment by zdravkov** [comment]
@crysper, what are the features that you need? Have you tried Kendo, I linked it a few replies up.

**Comment by maxt91** [comment]
So is the froala team still going to ignore paying customers? I'm still having to use the JS library and have to write my own bindings to force it to work. So far its been a great waste of money.

**Comment by therecluse26** [comment]
@maxt91 yeah, we've already migrated away from it from a future release. We were already migrating lots of components over to PrimeVue anyway, and their Quill-based editor is just as feature-complete, and much more up to date, also with a MUCH smaller footprint.

**Comment by crysper** [comment]
just the fact that they don't monitor the github issues and don't respond to comments, it's a red flag. I would understand if this was just a side project that some guys worked on their free time, but it's a paid product.

**Comment by maxt91** [comment]
@therecluse26  yeah, as soon as the license is up I will be going going away from this BS. thank you for the suggestion, will definitely be looking into it.

**Comment by ilyaskarim** [comment]
Our development team has been actively working on this issue, and I'm glad to announce that we are planning to release the fix around July 8th.

**Comment by ilyaskarim** [comment]
Vue3 framework upgrade is now available: https://froala.com/wysiwyg-editor/changelog/#4.1.0.

**Comment by joostgig** [comment]
> Vue3 framework upgrade is now available: https://froala.com/wysiwyg-editor/changelog/#4.1.0.

Too late now

**Comment by crysper** [comment]
where is the package for it?

**Comment by maxt91** [comment]
> Vue3 framework upgrade is now available: https://froala.com/wysiwyg-editor/changelog/#4.1.0.

your development team continues to ignore the needs of your customers. The new implementation still has same bugs that have been reported since 2020...

**Comment by jfk00ca** [comment]
> @ilyaskarim
> 
> > Vue3 framework upgrade is now available: https://froala.com/wysiwyg-editor/changelog/#4.1.0.
> 
> your development team continues to ignore the needs of your customers. The new implementation still has same bugs that have been reported since 2020...

I will echo this - last summer we spent almost 30 hours fixing a bug with iFrame alignment that caused the toolbar to go off-screen to the pop of the page, we submitted the hotfix, we have asked several times that our hotfix be deployed in builds going forward and expected it to be in this update... it is not... so even installing the updated toolbar on our side means we would have to spend 1.5 days to reimplement the hotfixes and we are seeing other bugs now as well.

This is incredibly frustrating and when I wrote to Froala support about this, because as much as we want Vue 3 compatibilty we are not going to upgrade our perpetual enterprise license if these things are not fixed in the update... they told me they could not talk to us unless we renew the license or place an order and not pay, which I am not comfortable with because placing an order creates the expectation that we owe them the money, no matter the outcome.

**Comment by gregpalaci** [comment]
Y'all need vite
