### ISSUE TITLE
Can't use custom buttom in quick insert tool bar

### ISSUE THREAD

**Issue by Artenes** [froala/vue-froala-wysiwyg#17]
I register a custom buttom:
```
$.FroalaEditor.RegisterCommand('alert', {
	title: 'Hello',
	focus: false,
	undo: false,
	refreshAfterCallback: false,
	callback: function () {
		alert('Hello!');
	}
});
```

I add the custom buttom to the `quickInsertButtons` option:

```

quickInsertButtons: ['alert']

```

And then nothing shows up when I click the quick insert buttom.

The quick insert buttom works as expected if I use other buttons:

```

quickInsertButtons: ['image', 'ul', 'li']

```

And my custom buttom shows up in the top toolbar:

```

toolbarButtons: ['alert'],

```

So, do I need to do something different to use a custom button in the quick insert toolbar?

**Comment by stefanneculai** [comment]
For now, it is not possible to use the toolbar buttons inside the quickInsertButtons: https://www.froala.com/wysiwyg-editor/docs/options#quickInsertTags
