### ISSUE TITLE
Uncaught TypeError: Cannot set property 'more_btn' of undefined

### ISSUE THREAD

**Issue by smety** [froala/vue-froala-wysiwyg#181]
Hi, 

in version 4.0.3 is bug: 

`Uncaught TypeError: Cannot set property 'more_btn' of undefined`

1. I marked the text
2. Added a link
3. Confirmed
4. Edited the link via the button
5. Modal freeze

**Comment by KrisAlexA** [comment]
Hi, I have the same issue but on resizing the browser window.

**Comment by rogerfar** [comment]
Downgrade to the latest 3.x version or wait for 4.0.4 because it's a bug that should be fixed in the next version.

**Comment by TheNoim** [comment]
well, 4.0.4 is there, and it isn't fixed. At least for me.

**Comment by challet** [comment]
Same problem when resizing the window. Though it doesn't seem to lead to any visual or functional issue.

**Comment by tommykjensen** [comment]
I also see this bug in 4.0.4
