### ISSUE TITLE
`enter` option doesn't work.

### ISSUE THREAD

**Issue by tuda-tq** [froala/vue-froala-wysiwyg#183]
There is the `enter` option, but it doesn't work.
https://froala.com/wysiwyg-editor/docs/options/#enter

I specified `FroalaEditor.ENTER_BR`, but the `p` tag will be used.

example:
https://jsfiddle.net/f7r5jL1b/

**Comment by pervaizdattoo** [comment]
It seems to be working well in your demo:
![image](https://user-images.githubusercontent.com/45271745/176508928-94e07220-83b8-4de5-9a48-4679432f3b57.png)
