### ISSUE TITLE
keydown event to detect a special key and insert some foobar

### ISSUE THREAD

**Issue by StefanNeuser** [froala/vue-froala-wysiwyg#19]
The Editor is initialized. Keydown becomes fired and my event listener is called. Could you please give some examples how to access the Editor and add Content like a hyperlink? 

```
                froalaConfig: {
                    events: {
                        'froalaEditor.initialized': function (initControls) {

                        },
                        'froalaEditor.keydown': function (e, editor, keyupEvent) {

                        },
                    }
                },
```

**Comment by stefanneculai** [comment]
@StefanNeuser the editor is being available in the editor param and it can be used to trigger any method from our docs like this: `editor.methodName();`.

**Comment by StefanNeuser** [comment]
Hi Stefan, thanks for the fast reply:

```
'froalaEditor.keydown': function (e, editor, keyupEvent) {
    editor('html.insert', 'foo bar', true);
},
```

causes in 

```
Uncaught TypeError: editor is not a function
    at HTMLTextAreaElement.froalaEditor.keydown (4:672)
    at HTMLTextAreaElement.dispatch (jquery.js:5206)
    at HTMLTextAreaElement.elemData.handle (jquery.js:5014)
    at Object.trigger (jquery.js:8201)
    at jQuery.fn.init.triggerHandler (jquery.js:8275)
    at v (froala_editor.pkgd.min.js:7)
    at HTMLDivElement.<anonymous> (froala_editor.pkgd.min.js:7)
    at HTMLDivElement.dispatch (jquery.js:5206)
    at HTMLDivElement.elemData.handle (jquery.js:5014)
```

**Comment by stefanneculai** [comment]
That's because you should call it like this: `editor.html.insert('foo bar', true);`. In the docs from our website, we're highlighting how to call using the jQuery way, not the editor object itself.

**Comment by StefanNeuser** [comment]
Ok thank you that works. I think the Docs are not really clear.

**Comment by stefanneculai** [comment]
@StefanNeuser we're constantly looking to improve it. If you have any feedback about how this could be explained better in the docs, that would be really helpful. Thanks in advance.
