### ISSUE TITLE
Crash with code view

### ISSUE THREAD

**Issue by Goldfinch** [froala/vue-froala-wysiwyg#2]
I have played with a demo and was thinking to buy a license, but found a weird bug. When quickly make some paragraphs (typing something and pressing enter, probably more than 3 times) or just add a youtube video and once you try to switch into the **Code view** - it's freezing, and actually sometimes after you even can't just close the current tab with the editor, need to rerun the browser.

Chrome, Firefox, Safari - the same bug

**Comment by SergioCrisostomo** [comment]
@Goldfinch can you make a jsFiddle/condepen?

**Comment by stefanneculai** [comment]
@Goldfinch indeed, a jsFiddle/codepen would be really helpful.

**Comment by stefanneculai** [comment]
Closing this due to lack of response. We'd be happy to look again into it if you could provide details to reproduce it.
