### ISSUE TITLE
vue-froala-wysiwyg with Typescript

### ISSUE THREAD

**Issue by anrolmar** [froala/vue-froala-wysiwyg#215]
Hi.

I'm using the froala editor in a VueJS project with Typescript:

- VueJS version: 2.7
- NodeJS version: 18.X

I'm having issues regarding the types, that they're not in the last version of the library 4.16.

As a first workaround, I did the solution from here, https://github.com/froala/wysiwyg-editor/issues/2369#issuecomment-507637238, but it didn't work because I need types for FroalaInitControls and FroalaJQueryElement

Do you know when these types are going to be ready to use?

**Comment by CreativeWarlock** [comment]
Would be interested too. Any ETA on this?

**Comment by ilyaskarim** [comment]
Type Definitions are now available in V4.1: https://froala.com/wysiwyg-editor/changelog/#4.1.0
