### ISSUE TITLE
image.insert() alaways insert at the head

### ISSUE THREAD

**Issue by pasBone** [froala/vue-froala-wysiwyg#23]
I use a different image response?
`$('.selector')
  .froalaEditor()
  .on('froalaEditor.image.uploaded', function (e, editor, response) {
    // Parse response to get image url.
    var img_url = ... ;
    editor.image.insert(img_url);
  });`
like this. but image.insert() alaways insert at the head. how do I？
thanks

**Comment by stefanneculai** [comment]
@pasBone most likely the editor is losing the selection when you click something else on the page. Before clicking something else, store selection with `selection.save` method and then restore it back with `selection.restore` before calling `image.insert`.
