### ISSUE TITLE
Drop event not working

### ISSUE THREAD

**Issue by denimpax** [froala/vue-froala-wysiwyg#25]
Drop event not working after drop text or image to editor area.

**js:**
> new Vue({
    el: '#article_editor',
    data: {
        froalaOptions: {
            language: 'ru',
            toolbarInline: true,
            charCounterCount: false,
            toolbarButtons: ['bold', 'italic', 'underline', 'strikeThrough', 'subscript', 'superscript', '-', 'paragraphFormat', 'align', 'formatOL', 'formatUL', 'indent', 'outdent', '-', 'insertImage', 'insertLink', 'insertFile', 'insertVideo', 'undo', 'redo'],
            toolbarVisibleWithoutSelection: true,
            events: {
                'froalaEditor.drop': function () {
                    console.log('drop');
                    return false;
                }
            }
        },
        text: 'text example',
    }
});

**html**
> `<froala v-model="text" :config="froalaOptions"></froala>`

But other events (focus, click, etc..) working normally

**Comment by stefanneculai** [comment]
@denimpax please use the drop event as described on our website demo: https://www.froala.com/wysiwyg-editor/examples/drop-content.

**Comment by arifhussain353** [comment]
In above example isn't mean that we have to initialize Froala with JQuery instead of VueJs ?.
