### ISSUE TITLE
Unknown custom element: <froala>

### ISSUE THREAD

**Issue by insub** [froala/vue-froala-wysiwyg#27]
My project use vue but it is not a SPA,  i try to include vue-froala like that: 
`<script src="/libs/froala_editor-2.7.0/js/vue-froala.js"></script> `
and use it:
`<froala :tag="'textarea'" :config="config" v-model="newWork.body"></froala>`
But console error:
`Unknown custom element: <froala> - did you register the component correctly? ...
`

So i try set this line :
`<script type="text/javascript">
Vue.component('froala', VueFroala)
</script>
`
Then  get console error:
`Uncaught ReferenceError: VueFroala is not defined`

I know i can import vue froala if i use .vue file like that:
```
import VueFroala from 'vue-froala-wysiwyg'
Vue.use(VueFroala)
```

But if i want to use vue-froala without .vue , how can i make it work ?

Thk~

**Comment by doydoydoy** [comment]
Any updates on this? I've been getting an error for this part as well. Current error is: 

> Unknown custom element: <froala> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by allanedk** [comment]
Did you find a solution to this? I'm having the same issue.

Thanks.

**Comment by Mboulianne** [comment]
if you wanna use vue-froala without vue, why not use https://github.com/froala/wysiwyg-editor instead?

**Comment by stefanneculai** [comment]
Guys, could you please provide details on how to reproduce this? If we get enough details to reproduce it on our side, we might be able to help.

**Comment by afwn90cj93201nixr2e1re** [comment]
@stefanneculai we wanna use it in single component, not on all bundle.
Like
```
import { Froala, FroalaView} from 'froala path'
components:{'froala-view':FroalaView},
```

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/froala/vue-froala-wysiwyg/pull/93/commits/2473356af79bcb8dbfe9d13db6f7aef7dd8de15e#diff-d06086d739c9878b4e3fcd66aba35062R322

**Comment by allanedk** [comment]
Did anybody find a solution to this?

I have a CMS-driven website which is not a SPA and not a Vue application. However, I'm using Vue in some situations to make pages partially driven by client-side code. It works fine.

However the current Froala Vue (vue-froala-wyswiyg) seems to only work in a dedicated Vue app / SPA.

For comparison: The Vue version of TinyMCE lets you add the editor directly in the HTML (no compiling etc.) like this:

```
<script src="/path/to/tinymce.min.js"></script>
```

And adding this before initializing the Vue app: 

```
Vue.component("editor", Editor);
```

Or like this:

```
 new Vue({
            el: "#app",
            components: {
                editor: Editor
            }
        });
```

It's easy and fast. 

I've been spending hours now on Froala. Am I missing something or will it require a change in Froala Vue to work like this?
