### ISSUE TITLE
How to add License Key

### ISSUE THREAD

**Issue by joancc** [froala/vue-froala-wysiwyg#28]
What is the best way to pass the license key to the Vue Froala Editor.
I've tried the following:

Note I'm still in development mode in localhost, not sure if adding the license at this stage will work.

Thanks!

1)
$('froala-editor').froalaEditor({
   key: 'XXXXXXXXXX'
})

2) 
data() {
    return {
      config: {
        events: {
          'froalaEditor.initialized': function() {
            console.log('initialized')
            $('froala-editor').froalaEditor({
              key: 'XXXXXXXXXX',
            })
          },
        },
        key: 'XXXXXXXXXX',
      },
      model: 'Edit Your Content Here!',
      key: 'XXXXXXXXXX',
    }
  },

**Comment by stefanneculai** [comment]
It should be passed as an option: https://github.com/froala/vue-froala-wysiwyg#options.
