### ISSUE TITLE
how to set set size . 

### ISSUE THREAD

**Issue by milowoo** [froala/vue-froala-wysiwyg#30]
hello:  i want to init set size , like this:

```js
 <froala :tag="'textarea'" :autosize="{minRows: 10,maxRows: 20}" 
    :config="config"   model="form.description"></froala>
```
 but it do not work .

**Comment by milowoo** [comment]
<froala :tag="'textarea'" :autosize="{minRows: 10,maxRows: 20}" 
    :config="config"   model="form.description"></froala>

**Comment by stefanneculai** [comment]
See https://www.froala.com/wysiwyg-editor/examples/adjustable-height.
