### ISSUE TITLE
How to use froala plugins

### ISSUE THREAD

**Issue by brweber2** [froala/vue-froala-wysiwyg#34]
We tried using the 'code_view' plugin and the javascript is loaded by the browser, but we never see the actual code view button. We've tried various webpack configuration changes and it dawned on me that an example of how to load froala plugins for use with this Vue component would be a perfect addition to the README file.

Thanks.

**Comment by stefanneculai** [comment]
@brweber2 if you are importing 'froala-editor/js/froala_editor.pkgd.min' then all the plugins should be there.

**Comment by brweber2** [comment]
Thanks, that fixed it. As dumb of a mistake as it was on my part, it might not be a bad idea to point out that 
`import 'froala-editor` 
will not include the plugins while the following will
`import 'froala-editor/js/froala_editor.pkgd.min'` 
Just a guess that I won't be the last one to make this mistake...

Thanks again!
