### ISSUE TITLE
emoji not show

### ISSUE THREAD

**Issue by solarwalker** [froala/vue-froala-wysiwyg#35]
with `useClasses: false`, froala will use inline style, it works perfect except emojis not showing in `froalaView` nor other doms.

![image](https://user-images.githubusercontent.com/1202134/35494136-68d94a3c-04f3-11e8-8591-6964be5e95e4.png)

the problem is `background` was setted to just `https`, not `https://cdnjs.cloudflare.com/ajax/libs/emojione/2.0.1/assets/svg/1f600.svg`

is it a bug or am i wrong in using?

thanks

**Comment by ngem** [comment]
ok, it is a bug, it is wrong when parsing style like 'background: url(https:/xxx.yyy)'

see file `froala_editor.pkgd.min.js`

![image](https://user-images.githubusercontent.com/1202134/35505467-28ea2d32-0521-11e8-8646-6223026c13f2.png)

**Comment by ngem** [comment]
just replace 

`(g[e].style[w[f].split(":")[0].trim()] = w[f].split(":")[1].trim())`

with

`(g[e].style[w[f].split(": ")[0].trim()] = w[f].split(": ")[1].trim())`
