### ISSUE TITLE
Image delete not working with imageManagerDeleteURL

### ISSUE THREAD

**Issue by Libinjoseph** [froala/vue-froala-wysiwyg#36]
I need to delete an uploaded image from my server if image is removed from editor. I have the following in the config
`imageManagerDeleteURL : myServer + '/delete-upload'`
When I remove the image, it is removed from editor, but no request to server is made.

**Comment by stefanneculai** [comment]
@Libinjoseph are you removing the image via the image manager or by clicking the image and hitting the remove button?

**Comment by novikov1337danil** [comment]
> @Libinjoseph are you removing the image via the image manager or by clicking the image and hitting the remove button?

The request is not sent to the server in both cases.
