### ISSUE TITLE
How to include Wiris plug-in?

### ISSUE THREAD

**Issue by sikhlana** [froala/vue-froala-wysiwyg#37]
I'm trying to add [Wiris](http://www.wiris.com/en/solutions/froala) to my editor but the buttons are not being added (I've included the buttons through the `:config` attribute).

I've followed their installation instructions and the tests are all positive. I've added Froala via NPM, compiling it with Laravel Mix (uses webpack).

**Comment by stefanneculai** [comment]
@sikhlana for any troubles regarding the Wiris integration please contact directly the Wiris team. They've made the integration and should have more details about that.
