### ISSUE TITLE
Add CustomIcon and RegisterCommand

### ISSUE THREAD

**Issue by DaFunkyAlex** [froala/vue-froala-wysiwyg#39]
Is there a way to add a custom icon and command as described in https://www.froala.com/wysiwyg-editor/docs/concepts/custom/dropdown?

It is only described how to do this with jQuery, how to do this in vue?

**Comment by stefanneculai** [comment]
@DaFunkyAlex the easiest way would be to use the code from our website after including the main editor js:

```js
// Require Froala Editor js file.
require('froala-editor/js/froala_editor.pkgd.min')
```

**Comment by WillCohenInfotrack** [comment]
@stefanneculai  less than helpful

**Comment by brayanph** [comment]
> @stefanneculai less than helpful

import FroalaEditor from 'froala-editor';

FroalaEditor.DefineIcon('imageInfo', {NAME: 'info', SVG_KEY: 'help'});
FroalaEditor.RegisterCommand('imageInfo', {})

**Comment by jg-jgriffith** [comment]
How do we do this now in Vue 3? 

I've tried including this with the above method, also with using VueFroala, and both stop the app from rendering.
