### ISSUE TITLE
Is jQuery required?

### ISSUE THREAD

**Issue by jackbarham** [froala/vue-froala-wysiwyg#4]
I know this has already been asked but I'm bit confused as a recent commit suggests that you have removed the dependency https://github.com/froala/vue-froala-wysiwyg/commit/d061484d7a35fbd0292ce43f128645e177d79fe6 but there is mention of requiring jQuery in the docs https://github.com/froala/vue-froala-wysiwyg#2-make-sure-you-have-the-right-webpack-settings-for-loading-the-css-files-font-awesome-and-jquery

Is it possible to use this without jQuery now? 

Thanks.

**Comment by stefanneculai** [comment]
@jackbarham no, it is not possible. jQuery is for now a dependency for the editor. There is going to be an update for that in the following months.
