### ISSUE TITLE
Editor disappearing

### ISSUE THREAD

**Issue by VardgesK** [froala/vue-froala-wysiwyg#40]
After writing many character editor disappearing.Console output this error.Uncaught TypeError: Cannot read property 'VOID_ELEMENTS' of null. What can i do?

**Comment by stefanneculai** [comment]
@VardgesK please reach us via https://www.froala.com/wysiwyg-editor/contact for more details.

**Comment by morwalz** [comment]
Same issue happening with angular version of this. 
https://github.com/froala/angular-froala-wysiwyg

No fix so far.

**Comment by canhazn** [comment]
Same issue
Maybe because I have no licence, there is no issue in local mode.

**Comment by malwareoverflow** [comment]
https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40
https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40https://github.com/froala/vue-froala-wysiwyg/issues/40

**Comment by davidnknight** [comment]
Also experiencing this with the angular version. Tried Googling and searching their FAQ for confirmation that this is because it's currently running in unlicensed mode but can't find anything so I have contacted their support.

If this is indeed the case, it could have been made more clear with a console error along the lines of "Your Froala editor has reset to a standard textarea because you are running an unlicensed copy. This does not happen with a licensed copy." because otherwise there's a real risk that it could be perceived as a bug and developers lose confidence and abandon it in search of another editor.

Either way, not a great first impression and not everyone wants to go to the effort/hassle of having to Google/search for answers so early into an integration. Let's hope support reply fast otherwise I may have to look elsewhere myself.
