### ISSUE TITLE
Modern Typescript and Vue

### ISSUE THREAD

**Issue by SmarterPhoneLabs** [froala/vue-froala-wysiwyg#43]
I see that this codebase has not been updated in quite a while.
Has anyone had luck getting this to work in newer versions of Typescript and Vue?
The "require" approach just isnt working and there is a need here to user actual imports on types.

Anyone made this work ?

**Comment by Mboulianne** [comment]
I'm having the same problem... haven't found a fix yet

**Comment by shreypasari-accolite** [comment]
Hi,
It is working fine for me. The require statements are not showing any error.

**Comment by stefanneculai** [comment]
@SmarterPhoneLabs @Mboulianne looks like per @shreypasari-accolite in the latest versions this problem is not there anymore. Would be extremely helpful if you could confirm. Thanks in advance!
