### ISSUE TITLE
change toolbarButtons at run time

### ISSUE THREAD

**Issue by shigg1120** [froala/vue-froala-wysiwyg#44]
I am passing "toolbarButtons" at run time as a prop
```
<app-wysiwyg :dynamic-config="{toolbarButtons: ['insertImage']}"></app-wysiwyg>

```

and assign it in `mounted()` hook
```
mounted() {
    this.config.toolbarButtons = this.dynamicConfig.toolbarButtons;
}
```

However, it won't change the buttons. Is there any way to change which buttons to show at run time through `props`?

I need to configure a different button per instance.

@stefanneculai

**Comment by stefanneculai** [comment]
The editor options cannot be changed after it was initialized. The best way is to destroy the editor instance and initialize it again with the new ones.
