### ISSUE TITLE
Can't access to component data from event

### ISSUE THREAD

**Issue by benoitvb** [froala/vue-froala-wysiwyg#45]
Hello,
I need to send params before uploading an image file.
I've tried this but without success...

` events: {
     'froalaEditor.image.beforeUpload': function (e, editor, images) {
        editor.opts.imageUploadParams['pageId'] = this.pageData.id
}`

I guess I'm out of the component scope but I don't know how to figure this out.
Is there another way to get datas from my component ? 

Thanks !
B

**Comment by shahilg** [comment]
Hi @stefanneculai ,

I am facing the same issue. I am using the editor with VueJS and not able to use the properties of data in the event of the editor.

`events: {
                'froalaEditor.blur': function(e, editor) {
                    console.log(this.valid)
                    if (editor.core.isEmpty) {
                        validator.validate('content')
                    }
                }
            }`

this.valid hold the boolean value but I get undefined in the event.
Looking forward to your inputs on this.

Thanks!

**Comment by stefanneculai** [comment]
@shahilg thanks for the details. Inside the callbacks, `this` is the editor context, not the context from the page. That is why you're getting these problems.

**Comment by Taxman972** [comment]
@stefanneculai , how can I pass data to the event ? The following code isn't working

<pre>
export default {
    data () {
        return {
            customId: 'test',
            config: {
                ...
               'froalaEditor.blur': function (e, editor, event, customId) {
                   console.log(customId) // show 'undefined'
               }
            }
            ...
</pre>
