### ISSUE TITLE
Call methods

### ISSUE THREAD

**Issue by alirzayev** [froala/vue-froala-wysiwyg#47]
Can you show an example for calling the method in vue component?

**Comment by Taxman972** [comment]
While reading the doc again I found the [answer](https://github.com/froala/vue-froala-wysiwyg#events-and-methods) .

**Comment by stefanneculai** [comment]
You could also use the manual initialization where you get better and more granular control: https://github.com/froala/vue-froala-wysiwyg#manual-instantiation.
