### ISSUE TITLE
Creating a working demo

### ISSUE THREAD

**Issue by Taxman972** [froala/vue-froala-wysiwyg#49]
Hi, I have multiple problem with vue-froala so could you create a working demo with [CodeSandBox](https://codesandbox.io) we could use as test base when reporting issue please.

**Comment by stefanneculai** [comment]
Thanks for the suggestion, @Taxman972.

**Comment by shreypasari-accolite** [comment]
Hi @stefanneculai,
Cant create an example on CodeSandBox because cant babel web config cannot be added there which is required for froala.
We can create a public repo for example of froala editor with VueJS.
Thank You

**Comment by shreypasari-accolite** [comment]
https://codesandbox.io/s/00p723krvv
A working demo on CodeSandBox
