### ISSUE TITLE
Using froala in modern environment

### ISSUE THREAD

**Issue by Mboulianne** [froala/vue-froala-wysiwyg#50]
To sum it up, it is pretty much the same thing as this issue =>
https://github.com/froala/wysiwyg-editor/issues/1668

We don't want to have to define a global jquery variable when we use vue froala.  jQuery should be imported / required instead of being used as a global variable.

If this isn't fixed this will be a dealbreaker for us and we'll let go of froala and use tiny / ck instead.  We want to be able to chunk / bundle froala (and its dependencies) with webpack.  Therefore, webpack.providePlugin is a big no go for us.

Thank you.

**Comment by Mboulianne** [comment]
@stefanneculai I've seen you've worked on a similar fix before.

**Comment by stefanneculai** [comment]
@Mboulianne this is going to be addressed in the next major release that we're going to make and in which we're going to remove jQuery. For now, we don't have an ETA that we could share public, however, updates should come on [our blog](https://www.froala.com/blog) shortly.

**Comment by ty7466** [comment]
Current documentation still states that you need to use the ProvidePlugin. Has JQuery been removed?
