### ISSUE TITLE
toggling v-if on froala component create duplicate textarea

### ISSUE THREAD

**Issue by Mboulianne** [froala/vue-froala-wysiwyg#51]
I have the following HTML =>
```
<froala :tag="tag" :config="internalOptions" :value="value" @input="refreshModel" v-if="!readOnly"></froala>
```

with a button that allows me to toggle readonly on and off.  

Each time readOnly === true (froala is removed from the dom) a new textarea is created.

And I end up with something like this
![image](https://user-images.githubusercontent.com/18729439/41978769-79c5dd84-79f0-11e8-9909-8c7f7ebb52b1.png)

As a workaround I can change my HTML to be
```
<div v-if="!readOnly">
    <froala :tag="tag" :config="internalOptions" :value="value" @input="refreshModel"></froala>
</div>
```

but it's sad to have to create a div for this purpose.

**Comment by stefanneculai** [comment]
Unfortunately, there is not too much we could do - this looks hardly linked to how `v-if` works on adding/removing elements from the DOM.
