### ISSUE TITLE
Initialization should not change / format code

### ISSUE THREAD

**Issue by steffanhalv** [froala/vue-froala-wysiwyg#52]
##### Expected behavior.
No changes should be done to source before interactively using the editor.

##### Actual behavior.
The source is formatted / cleaned on initialization

##### Details.
We have reactive source with watchers for code edited by Froala editor.
If changes are made, a notice is added to users which sees 'Unsaved changes' so they dont forget to save their text.

Froala editor is modifying the source on initialization which applies the 'changed content' notice.

It would be much better if source is not touched before interactively using the editor.

##### Steps to reproduce the problem.
Initialize a textarea with html code in value

##### OS.
macOS High Sierra, Win 10 etc..

##### Browser.
Chrome, firefox, ie, safari, opera etc.. Latest

Ref. https://github.com/froala/wysiwyg-editor/issues/2936

**Comment by stefanneculai** [comment]
The editor is doing an initial a clean-up on the HTML in order to make it display correctly on the editor and follow the options the editor is initialized with. The contentChanged event shouldn't be triggered at this moment. Are you using the `contentChanged` event to get changes inside the editor?
