### ISSUE TITLE
Editor freezes after quick clicking on table cells and/or inserting nested tables

### ISSUE THREAD

**Issue by elkesrio** [froala/vue-froala-wysiwyg#53]
Editor and toolbar become disabled after quick clicking on table cells and/or inserting nested tables.
(found the same issue here: https://github.com/froala/wysiwyg-editor/issues/2299). I can re-enable it by setting `contenteditable` to true to this element `div.fr-wrapper.show-placeholder > div`

**Comment by stefanneculai** [comment]
@elkesrio are you able to reproduce this on our website? Could you maybe send us a recording of that?
