### ISSUE TITLE
how to change response

### ISSUE THREAD

**Issue by mcmf** [froala/vue-froala-wysiwyg#54]
upload response as  {"link":"http://i.froala.com/images/missing.png"}

How to change the received value as 

`{"code":1,"msg":"success","time":1531364761,"data":{"url":"http:\/\/api.com:80\/uploads\/20180712\/1cf6534853175fe7bdc509c49b75c241.jpg","link":"http:\/\/api.com:80\/uploads\/20180712\/1cf6534853175fe7bdc509c49b75c241.jpg"}}`

**Comment by stefanneculai** [comment]
See https://wysiwyg-editor.froala.help/hc/en-us/articles/115000593909-How-can-I-use-a-different-image-response-.
