### ISSUE TITLE
No way to setup events to bind before others

### ISSUE THREAD

**Issue by gabaum10** [froala/vue-froala-wysiwyg#58]
it looks like there is no way to bind your events before any of the internal froala ones.  For example: https://github.com/froala/wysiwyg-editor/issues/1258#issuecomment-219121345

If you passed true at the time of binding it would bind before the internal events.  I need this to prevent enter from adding a new line.  This is necessary for a message application where "enter to send" is enabled.

**Comment by gabaum10** [comment]
Perhaps a modifier on the event namespace?  

I was able to work around this by keeping a local reference to the editor inside my wrapper component and binding the event the old way in a watcher.  For example:

```javascript
{
  watch: {
    editor () {
        if (!this.editor) {
          return
        }
        this.editor.events.on('keydown', function (_e) {
          if ((_e.which === 13 || _e.which === 10)) {
            if (_e.shiftKey) {
              this.editor.cursor.enter()
            } else {
              this.$emit('enterClicked')

              if (this.disableNewLine) {
                _e.stopImmediatePropagation()
                _e.preventDefault()
                // I have no idea why stopImmediatePropagation and preventDefault are not enough,
                // but w/e return false here to "force" the event to stop here?
                return false
              }
            }
          }
        }.bind(this), true)
      }
  }
}
```

**Comment by stefanneculai** [comment]
@gabaum10 the best way would be to use the initialized event and inside the initialized event bind to events by passing the `true` param as well.
