### ISSUE TITLE
Hidden textarea isn't destroy

### ISSUE THREAD

**Issue by EreHuc** [froala/vue-froala-wysiwyg#59]
Hi there ! French dev here, bad english incoming ;)

When you set the tag to `textarea` to Froala and you toggle it with a v-if the editor hidden textarea is not removed and it will be display (inline style `display:hidden` is remove).

And when you do it multiple time Froala keep re-creating textarea but don't destroy them.

There is no problem when you set tag to `div` or `span`.

**Comment by stefanneculai** [comment]
@EreHuc do you think you could create a demo to show this? That would be of tremendous help.
