### ISSUE TITLE
Switched to babel7. present-env. Froala error node_modules for stringify

### ISSUE THREAD

**Issue by ezikialbasix** [froala/vue-froala-wysiwyg#60]
Hello,

I've recently upgrade my project to use babel 7.1.  Upon upgrading I noticed that the package for vue-froala is pointing to:
`var _stringify = require('babel-runtime/core-js/json/stringify');`
when it should be:
`var _stringify = require('core-js/fn/json/stringify');`

Any tips on how to make this work?  It seems that they have have migrated away from that runtime or something?

thanks

**Comment by enbermudas** [comment]
I'm having the same problem!

**Comment by rebz** [comment]
I am experiencing this as well.

**Comment by Budy-Love** [comment]
Really annoying, please move forward.

**Comment by stefanneculai** [comment]
@ezikialbasix @enbermudas @rebz @Budy-Love could any of you make a PR for it? Thanks in advance.
