### ISSUE TITLE
Broken code view mode

### ISSUE THREAD

**Issue by Asxer** [froala/vue-froala-wysiwyg#74]
Hello! Thank you for amazing plugin! It's very helpful but I have trouble with code view mode.

When I click on Code View button editor looks like this:

![image](https://user-images.githubusercontent.com/6561224/54981266-170d8800-4fd2-11e9-847e-aab396f92fb0.png)

I've used your plugin in my old project and everything works properly. Could you please help me to fix it?

**Comment by stefanneculai** [comment]
Looks like you are not including the CSS file for the Code View plugin. Please make sure that you include both JS and CSS files for the plugin.
