### ISSUE TITLE
Module not found: Can't resolve 'babel-runtime/core-js/json/stringify'

### ISSUE THREAD

**Issue by wangjacsi** [froala/vue-froala-wysiwyg#75]
when running "npm run watch" in Laravel 5.8 I got this error :
(version npm: 6.8.0, node 11.3, webpack: 4.29.6)
I think it's because of version conflict. 

ERROR in ./node_modules/vue-froala-wysiwyg/es/vue-froala.js
Module not found: Error: Can't resolve 'babel-runtime/core-js/json/stringify' in '/Users/sean/Sites/codewwwave/node_modules/vue-froala-wysiwyg/es'
 @ ./node_modules/vue-froala-wysiwyg/es/vue-froala.js 7:17-64
 @ ./node_modules/vue-froala-wysiwyg/es/index.js
 @ ./resources/assets/js/pages/tutorial/edit.js
 @ multi ./resources/assets/js/pages/tutorial/edit.js

**Comment by zacksmash** [comment]
Exact same error for me.

**Comment by stefanneculai** [comment]
What `babel-runtime` do you have?

**Comment by zacksmash** [comment]
I don’t see that library in my project, at all.

**Comment by stefanneculai** [comment]
Does it work if you do `npm install --save babel-runtime`?

**Comment by zacksmash** [comment]
@stefanneculai Yeah, that works. Any idea why that's not brought in when I install `vue-froala-wysiwyg`, automatically?

**Comment by stefanneculai** [comment]
It was added in our `package.json` recently and we haven't put a release update since then: https://github.com/froala/vue-froala-wysiwyg/blob/master/package.json#L45.
