### ISSUE TITLE
Illegal invocation

### ISSUE THREAD

**Issue by iyyann** [froala/vue-froala-wysiwyg#85]
froala_editor.min.js:1 Uncaught TypeError: Illegal invocation
    at Node.get (froala_editor.min.js:1)
    at froala_editor.pkgd.min.js:1
    at froala_editor.pkgd.min.js:1
    at Object../node_modules/froala-editor/js/froala_editor.pkgd.min.js (froala_editor.pkgd.min.js:1)
    at __webpack_require__ (bootstrap:766)
    at fn (bootstrap:129)
    at Object../node_modules/vue-froala-wysiwyg/es/vue-froala.js (vue-froala.js:15)
    at __webpack_require__ (bootstrap:766)
    at fn (bootstrap:129)
    at Object../node_modules/vue-froala-wysiwyg/es/index.js (index.js:13)

my plugins/froala.js
// Import Froala Editor css files.
import 'froala-editor/css/froala_editor.pkgd.min.css';
import 'froala-editor/css/froala_style.min.css';

// Import and use Vue Froala lib.
import 'froala-editor/js/languages/zh_cn.js'
import VueFroala from 'vue-froala-wysiwyg'
import FroalaEditor from 'froala-editor/js/froala_editor.pkgd.min';
import Vue from 'vue'
Vue.use(VueFroala)

**Comment by iyyann** [comment]
"devDependencies": {
        "@babel/core": "^7.4.3",
        "@babel/runtime-corejs2": "^7.4.4",
        "babel-eslint": "^10.0.1",
        "babel-loader": "^8.0.5",
        "babel-plugin-dynamic-import-webpack": "^1.1.0",
        "babel-plugin-syntax-dynamic-import": "^6.18.0",
        "clean-webpack-plugin": "^2.0.0",
        "css-loader": "^2.1.1",
        "eslint": "^5.16.0",
        "eslint-plugin-vue": "^5.2.2",
        "file-loader": "^3.0.1",
        "html-webpack-plugin": "^3.2.0",
        "js-cookie": "^2.2.0",
        "mini-css-extract-plugin": "^0.6.0",
        "node-sass": "^4.12.0",
        "nprogress": "^0.2.0",
        "optimize-css-assets-webpack-plugin": "^5.0.1",
        "px2rem-loader": "^0.1.9",
        "sass-loader": "^7.1.0",
        "style-loader": "^0.23.1",
        "terser-webpack-plugin": "^1.2.3",
        "url-loader": "^1.1.2",
        "vue-loader": "^15.7.0",
        "vue-moment": "^4.0.0",
        "vue-style-loader": "^4.1.2",
        "vue-template-compiler": "^2.6.10",
        "webpack": "^4.30.0",
        "webpack-bundle-analyzer": "^3.3.2",
        "webpack-cli": "^3.3.0",
        "webpack-dev-server": "^3.3.1"
    },
    "dependencies": {
        "axios": "^0.18.0",
        "element-ui": "^2.8.2",
        "vue": "^2.6.10",
        "vue-froala-wysiwyg": "^3.0.0-beta.1",
        "vue-router": "^3.0.6",
        "vue-video-player": "^5.0.2",
        "vuex": "^3.1.1"
    },

**Comment by iyyann** [comment]
There's a problem with this code：import 'froala-editor/js/languages/zh_cn'

**Comment by akki744** [comment]
> There's a problem with this code：import 'froala-editor/js/languages/zh_cn'

@iyyann You don't need to include any language file now. Everything is included in pkgd file by default. Can you try removing it and check it if it works?
Thanks

**Comment by stefanneculai** [comment]
Should be fixed in `3.0.0-beta.2`.
