### ISSUE TITLE
Model is not updated in HTML mode

### ISSUE THREAD

**Issue by AdrienPoupa** [froala/vue-froala-wysiwyg#88]
Even when I enable `immediateVueModelUpdate`, the model does not update when I am in the HTML mode.

This is a problem as this makes it impossible to save the user's content without going back to the WYSIWYG mode to update the model first.

You can reproduce it here: https://codesandbox.io/s/vue-template-zjik6

1. Type text in HTML mode
2. See that the model is not updated below the editor

**Comment by AdrienPoupa** [comment]
@stefanneculai please have a look

**Comment by ilyaskarim** [comment]
@stefanneculai any updates on this and are you able to reproduce the issue on https://codesandbox.io/s/vue-template-zjik6?

**Comment by AdrienPoupa** [comment]
Please see the following video that describes it
https://www.youtube.com/watch?v=IqTAjvEUwMs

**Comment by ilyaskarim** [comment]
Hi @AdrienPoupa Please see this youtube video I uploaded https://youtu.be/T-MF5I9GyQg, I used your same sanbox and it is working fine for me.

**Comment by AdrienPoupa** [comment]
You reproduced the exact issue we are talking about. The model should be updated as you type WHILE you are in the HTML mode, not when you exit it. Do you understand?

**Comment by ilyaskarim** [comment]
@AdrienPoupa This is not a bug. When you switch from code view to edit view. The editor is designed in a way that it copies data from textarea when you go to view mode.

**Comment by AdrienPoupa** [comment]
From the documentation: https://www.froala.com/wysiwyg-editor/docs/framework-plugins/vue

```
immediateVueModelUpdate: (default: false) This option updates the Vue model as soon as a key is released in the editor. Note that it may affect performances.
```

It should not care whether we are in HTML or WYSIWYG
