### ISSUE TITLE
this._$element.froalaEditor is not a function

### ISSUE THREAD

**Issue by imvicchen** [froala/vue-froala-wysiwyg#9]
[Vue warn]: Error in mounted hook: "TypeError: this._$element.froalaEditor is not a function"

**Comment by faforty** [comment]
I have the same error, I'll try to solve

**Comment by faforty** [comment]
@imvicchen 
Import js and css before import Vue component.
If you used ssr vue, then will check process.env.NODE_ENV == 'client'.

Problem solved.
