### ISSUE TITLE
toolbarButtons options

### ISSUE THREAD

**Issue by ZhangJunkang** [froala/vue-froala-wysiwyg#91]
I use toolbarButtons options，but many properties have no effect

**Comment by ZhangJunkang** [comment]
![DE)3P(1{X}X PJ7R~38_BYJ](https://user-images.githubusercontent.com/16699342/58544147-5014e380-8233-11e9-8269-7f6e20899813.png)
![E$_9R@YK%XNCPM1K$~6QMH1](https://user-images.githubusercontent.com/16699342/58544214-66bb3a80-8233-11e9-8195-c9eeb0133306.png)

**Comment by rbourque** [comment]
Same problem...   Anything with a flyover menu (colour, font, etc) doesn't display since the ^3.0.0 update.

**Comment by darki73** [comment]
You have to import plugins before you can use all of the features, the way i do it (no idea if it is wrong or right, since plugins are not ES6 modules, but it still works)
```
import Vue from 'vue';

// Base Plugin Scripts And Styles
import VueFroala from 'vue-froala-wysiwyg';
import 'froala-editor/css/froala_editor.pkgd.min.css';

// Character Counter Plugin Scripts and Styles
import CharactersCounter from 'froala-editor/js/plugins/char_counter.min';
import 'froala-editor/css/plugins/char_counter.min.css';

Vue.use(VueFroala, {
    plugins: [
        CharactersCounter
    ]
});
```

**Comment by pochocho** [comment]
The easiest way I have found to do this is if you need most or all plugins is to add the packaged plugins js file (plugins.pkgd.min.js) here is an example:

```
import Vue from 'vue'

import VueFroala from 'vue-froala-wysiwyg';
import 'froala-editor/css/froala_editor.pkgd.min.css';

import 'froala-editor/js/plugins.pkgd.min.js'

Vue.use(VueFroala);
```

**Comment by ZhangJunkang** [comment]
@pochocho thanks
