### ISSUE TITLE
Froala v3 rc.2 Did the jquery dependency get re-introduced?

### ISSUE THREAD

**Issue by pochocho** [froala/vue-froala-wysiwyg#94]
Just installed v3 rc.2 and had some errors and noticed that the jQuery dependency was re-introduced, was this intended or was it a mistake? One big plus I saw from v3 was removing that dependency. In the create editor function you can see:

**this._$element = jQuery(this.$el);**

in contrast to rc.1 where you would see:

**this._editor = new FroalaEditor(this.$el, this.currentConfig)**

**Comment by WillCohenInfotrack** [comment]
yes also experiencing this issue 
![image](https://user-images.githubusercontent.com/12131516/59040385-7c051a00-886e-11e9-9cc4-2ac79449dc86.png)

**Comment by navneetnagpal** [comment]
@pochocho we just fixed it and released new version vue-froala-wysiwyg@3.0.0-rc.2-1.

**Comment by pochocho** [comment]
@navneetnagpal thanks!
