### ISSUE TITLE
Cannot read property $off of undefined

### ISSUE THREAD

**Issue by nevaan9** [froala/vue-froala-wysiwyg#97]
I upgraded to 3.0.0. I had previous configs (which worked perfectly) and I saw this error. I removed all the configs and tried with the most basic config, but the error still persists.

it happens when my component that has the froala editor mounts. 

<img width="667" alt="Screen Shot 2019-06-17 at 10 10 37 AM" src="https://user-images.githubusercontent.com/20254162/59611311-183de500-90e9-11e9-970b-7442315ac5f6.png">

**Comment by i-ira** [comment]
Dealing with the same issue

**Comment by nevaan9** [comment]
@i-ira have you found out why?

**Comment by nevaan9** [comment]
@stefanneculai any idea why?
